{% set version = '0.1.1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-miniui
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/miniUI_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/miniUI/miniUI_{{ version }}.tar.gz
  sha256: 452b41133289f630d8026507263744e385908ca025e9a7976925c1539816b0c0

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-htmltools >=0.3
    - r-shiny >=0.13

  run:
    - r-base
    - r-htmltools >=0.3
    - r-shiny >=0.13

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('miniUI')"           # [not win]
    - "\"%R%\" -e \"library('miniUI')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=miniUI
  license: GPL-3
  summary: Provides UI widget and layout functions for writing Shiny apps that work well on small
    screens.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: miniUI
# Type: Package
# Title: Shiny UI Widgets for Small Screens
# Version: 0.1.1.1
# Authors@R: c( person("Joe", "Cheng", role = c("cre", "aut"), email = "joe@rstudio.com"), person(family = "RStudio", role = "cph") )
# Description: Provides UI widget and layout functions for writing Shiny apps that work well on small screens.
# License: GPL-3
# LazyData: TRUE
# Imports: shiny (>= 0.13), htmltools (>= 0.3), utils
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2018-05-18 17:00:34 UTC; jcheng
# Author: Joe Cheng [cre, aut], RStudio [cph]
# Maintainer: Joe Cheng <joe@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-05-18 18:37:18 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
