travis:
  secure:
    BINSTAR_TOKEN: fU3Tn9ltCXqfrYwYfBUr/FWnRw4wafRh0xTNAJRLdXWzsohGt8BeJhLmYeX7Adczfuzc7qbq1FtMUZsOHhcIpOIuwsZBEIgSYSSF/G1XrTOmPM1zUxT0NoCNYYyugMnbHCQKJXewM3DbRCp+sBddy4t7VvVjeXFNJAxogppTpRn7XaDuH2KqQy2o8Yz7AQYvrtnnZwrwUly6I/B0+Z483jPVYIW3E9/PAYilvGSHWGQDFvJGE6CU6fGZBYrZlJXCsZLCuJCAwcSEoYP6KqcmVDS9FYOx/KpLfppDERVpL86aKUbIHW3addPIV42/KhPPTzo8sdEdkAn6q83zK932vQ0HjpAOY1vMunl7B7Iakw3j1ksyZPe6PZ+Pkz4HYQxtDuaQ6yr6fKmUIOOut14YZzSQEU6b55AzMyEkKORTFuf7PApMVL2lRrGWAaRs/fwhqr6nt9BRxV2mE6w+AdE102DoSASAMJ61Xf3lPnu6ldS72Sgjbb/mpXOUKmtbI+vQZ7qrbIgS8EmQYiTyqVWJRivZiJd0p7QnlguhIPdpzQOVtfsVQqS1KgRQ+Afw7Fyw72syQ+qGb9P2KsvpEK79HU37jC6G6GEv/wt+lX43XLKkBtiopskAxiwUPMDePyoy4AeTI4l6vNlcPk+E44VgjvNoBgfqP2f9G/wHFWlnl/8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
