travis:
  secure:
    BINSTAR_TOKEN: KfkG89glrlQOF1h/+D9k/cb4ddTYqKgiBvFDJnelvHdnX8QUmatKEXRqIMcR0qWzKklMjqr7ZgeaZqvhRupz3MNyH5D6/cCxS9fzGjDsfaIXAoT4hYuiVBdt6tr3h2KVuwBW0kU/VL9vrH4dAjVRh5p55dbq6eu/RxgnETBmlkYqf7eYjYLYLUCj5xeEhexI3HcOTAblVDLUMmwQyEGYADKn7NkBspAsLzMDoa2CLj75MKnAJAQeP9vyQmFaSO5VAmaNkmsLErhbpgRSZ3Z4hwHImUO6dHrHkuyhAzLKkrFuClvfqyApHNn8gunJZU5h7s03XO2nyF7T1ebZ/BU2HiCXM76DZLLQ7PiY19NGE9k0UStF5eaSTyBeOk6tZAvAwwHzUnPvv5nWEnamw9UO+1zCMdRThezAMvUrnzU4ttO80e/s9G74amH77MJGOwO8HGMXMxL0cmRsKu37OePcKjfa6mo48XBgI4LTSQWyZ4MrTndV62k/2Alk667x2f954xqs8xoUFSFraE2JJ1IhzQYN5nRg/Km0u81qnIZVPGHM9NF+AR6e7D7VvvilORJzMjy4F1ZP3m+tr02nCLgVcZGraQHXB/XnH1KfOOTRft8qeAsHLRU1HZcz7efQk6SX+MG2vD88FxwRD5SgdLjo884DxEq29WmBV5tZNLUJomA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
